services:

  backend:
    build:
      context: ./backend
    container_name: automobile_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: automobile_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped