"""create attendance machinery robotics maintenance tables

Revision ID: 1a052782a881
Revises: 29712a8a9e0d
Create Date: 2026-08-14 14:40:39.795469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a052782a881'
down_revision: Union[str, Sequence[str], None] = '29712a8a9e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machinery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=150), nullable=False),
    sa.Column('machine_type', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('machine_status', sa.String(length=50), nullable=False),
    sa.Column('running_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_code')
    )
    op.create_index(op.f('ix_machinery_id'), 'machinery', ['id'], unique=False)
    op.create_table('robotics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('robot_code', sa.String(length=50), nullable=False),
    sa.Column('robot_name', sa.String(length=150), nullable=False),
    sa.Column('automation_type', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_cycle_days', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_code')
    )
    op.create_index(op.f('ix_robotics_id'), 'robotics', ['id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
    sa.Column('maintenance_cost', sa.Float(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('technician_name', sa.String(length=150), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machinery.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robotics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_logs_id'), 'maintenance_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_logs_id'), table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_robotics_id'), table_name='robotics')
    op.drop_table('robotics')
    op.drop_index(op.f('ix_machinery_id'), table_name='machinery')
    op.drop_table('machinery')
    # ### end Alembic commands ###
